[package]
name = "bign-handheld-thumbnailer"
version = "1.1.2"
authors = ["Mateus Rodrigues Costa <mateusrodcosta@gmail.com>"]
edition = "2021"
description = "A thumbnailer for Nintendo handheld systems (Nintendo DS and 3DS) roms and files"
readme = "README.md"
repository = "https://github.com/MateusRodCosta/bign-handheld-thumbnailer"
license = "GPL-2.0-or-later"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# This thumbnailer will at the very least be packaged as a RPM for Fedora
# Therefore the dependencies it uses must be compatible with what is available
# on Fedora repos for the currently supported Fedora releases
[dependencies]
pico-args = "0.5.0"
gio = "0.20.7"
thiserror = "2.0.9"

[dependencies.image]
version = "0.25.5"
default-features = false
features = ["png"]

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
